### ISSUE TITLE
Infografía de Hilos

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/infografia-de-hilos-Band-hi#2]
![Infografia Hilos](https://user-images.githubusercontent.com/46431649/117846346-f868ba80-b246-11eb-9114-da0cee1add47.png)

**Comment by IsraelNicolas61** [comment]
Calificación: 19

Calificó: Imanol García, Israel Nicolás y Uzias López

**Comment by josealfredo79** [comment]
Bien hecho y revisado
